// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrQbFNhHJ7YVtNCZEJ9gPIjY3xYfVdxEo',
    appId: '1:700292526751:web:c97fc5c38530bc191ba8aa',
    messagingSenderId: '700292526751',
    projectId: 'donasi-app-e23ee',
    authDomain: 'donasi-app-e23ee.firebaseapp.com',
    storageBucket: 'donasi-app-e23ee.firebasestorage.app',
    measurementId: 'G-B8E2E8GKS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mE6LRox0Srt-x8T17W33XlYfm2S1mKI',
    appId: '1:700292526751:android:210bdb268050814d1ba8aa',
    messagingSenderId: '700292526751',
    projectId: 'donasi-app-e23ee',
    storageBucket: 'donasi-app-e23ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4JpmakQsa3miyoxSYR6WZ16z0jQzagQ',
    appId: '1:700292526751:ios:f20ef3379579033d1ba8aa',
    messagingSenderId: '700292526751',
    projectId: 'donasi-app-e23ee',
    storageBucket: 'donasi-app-e23ee.firebasestorage.app',
    iosBundleId: 'com.example.donasiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv4JpmakQsa3miyoxSYR6WZ16z0jQzagQ',
    appId: '1:700292526751:ios:f20ef3379579033d1ba8aa',
    messagingSenderId: '700292526751',
    projectId: 'donasi-app-e23ee',
    storageBucket: 'donasi-app-e23ee.firebasestorage.app',
    iosBundleId: 'com.example.donasiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrQbFNhHJ7YVtNCZEJ9gPIjY3xYfVdxEo',
    appId: '1:700292526751:web:330b3d6a00f897231ba8aa',
    messagingSenderId: '700292526751',
    projectId: 'donasi-app-e23ee',
    authDomain: 'donasi-app-e23ee.firebaseapp.com',
    storageBucket: 'donasi-app-e23ee.firebasestorage.app',
    measurementId: 'G-QBNMYF2R7Z',
  );
}
